[package]
name = "aoe2-probe"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-or-later"
description = "A rust library for editing aoe2scenorio files from AoE2 DE."
homepage = "https://github.com/ptazithos/aoe2-probe"
repository = "https://github.com/ptazithos/aoe2-probe"
readme = "README.md"
keywords = ["gamedev", "AoE2DE", "parser"]
categories = ["game-development", "parsing"]

exclude = [
    "resources",
    "examples",
]


[dependencies]
log = "0.4.17"
miniz_oxide ="0.5.3"

[dev-dependencies]
env_logger = "0.9.0"


[[example]]
name = "read_write"
path = "examples/read_write.rs"

[[example]]
name = "serialize"
path = "examples/serialize.rs"

[[example]]
name = "template"
path = "examples/template.rs"

[[example]]
name = "print_info"
path = "examples/print_info.rs"

[[example]]
name = "update_attr"
path = "examples/update_attr.rs"


