version: 2.1


jobs:
  build:
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run: cargo --version
      - run: cargo build
  test:
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - run: cargo --version
      - run: cargo test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build


