version: 2.1

jobs:
  lint-test-build:
    docker:
      - image: cimg/rust:1.70.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ checksum "Cargo.toml" }}      
      - run: cargo --version
      - run: cargo clippy
      - run: cargo test
      - run: cargo build --verbose
      - save_cache:
          key: cargo-{{ checksum "Cargo.toml" }}
          paths: 
            - ~/.cargo

workflows:
  build_and_test:
    jobs:
      - lint-test-build



